version: "3.9"

services:

  frontend:
    image: abuabakaralnour/blog-frontend:v6
    ports:
      - "80:80"
    networks:
      - frontend
    deploy:
      replicas: 2

  api:
    image: abuabakaralnour/blog-api:v10
    secrets:
      - db_password
    networks:
      - frontend
      - backend

    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      rollback_config:
        parallelism: 1

  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password

    secrets:
      - db_password

    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7-alpine
    networks:
      - backend

networks:
  frontend:
    driver: overlay

  backend:
    driver: overlay

secrets:
  db_password:
    external: true

volumes:
  postgres-data:
